'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'id' | 'es' | 'fr' | 'de' | 'ja' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    search: "Search",
    explore: "Explore",
    messages: "Messages",
    notifications: "Notifications",
    create: "Create",
    profile: "Profile",
    work: "Work",
    settings: "Settings",
    logout: "Logout",
    pengaturan: "Settings",
    editProfil: "Edit Profile",
    notificationsMenu: "Notifications",
    accountPrivacy: "Account Privacy",
    closeFriend: "Close Friends",
    blocked: "Blocked",
    archiving: "Archiving & Downloading",
    language: "Language",
    editProfilTitle: "Edit Profile",
    loading: "Loading...",
    uploading: "Uploading...",
    ubahFoto: "Change Photo",
    hapusFoto: "Remove Photo",
    name: "Name",
    username: "Username",
    website: "Website",
    bio: "Bio",
    gender: "Gender",
    menyimpan: "Saving...",
    kirim: "Submit",
    notificationSettingsTitle: "Notification Settings",
    accountPrivacyTitle: "Account Privacy",
    closeFriendTitle: "Close Friends",
    blockedTitle: "Blocked Users",
    archivingTitle: "Archiving & Data Download",
    languageTitle: "Language Settings",
    remove: "Remove",
    unblock: "Unblock",
    downloadYourData: "Download Your Data",
    downloadDataDesc: "Download a copy of your Kollect data including profile, posts, campaigns, and works.",
    downloadAsJSON: "📥 Download as JSON",
    downloadAsCSV: "📊 Download as CSV",
    selectLanguage: "Select Your Language",
    english: "English (EN)",
    indonesian: "Bahasa Indonesia (ID)",
    spanish: "Español (ES)",
    french: "Français (FR)",
    german: "Deutsch (DE)",
    japanese: "日本語 (JA)",
    chinese: "中文 (ZH)",
    updating: "Updating...",
    goToLogin: "Go to Login",
    failedLoadProfile: "Failed to load profile",
    languageUpdated: "Language updated successfully!",
    failedUpdateLanguage: "Failed to update language",
  },
  id: {
    home: "Beranda",
    search: "Cari",
    explore: "Jelajahi",
    messages: "Pesan",
    notifications: "Notifikasi",
    create: "Buat",
    profile: "Profil",
    work: "Pekerjaan",
    settings: "Pengaturan",
    logout: "Keluar",
    pengaturan: "Pengaturan",
    editProfil: "Edit Profil",
    notificationsMenu: "Notifikasi",
    accountPrivacy: "Privasi Akun",
    closeFriend: "Teman Dekat",
    blocked: "Diblokir",
    archiving: "Pengarsipan & Unduhan",
    language: "Bahasa",
    editProfilTitle: "Edit Profil",
    loading: "Memuat...",
    uploading: "Mengunggah...",
    ubahFoto: "Ubah Foto",
    hapusFoto: "Hapus Foto",
    name: "Nama",
    username: "Nama Pengguna",
    website: "Situs Web",
    bio: "Bio",
    gender: "Jenis Kelamin",
    menyimpan: "Menyimpan...",
    kirim: "Kirim",
    notificationSettingsTitle: "Pengaturan Notifikasi",
    accountPrivacyTitle: "Privasi Akun",
    closeFriendTitle: "Teman Dekat",
    blockedTitle: "Pengguna Diblokir",
    archivingTitle: "Pengarsipan & Unduhan Data",
    languageTitle: "Pengaturan Bahasa",
    remove: "Hapus",
    unblock: "Buka Blokir",
    downloadYourData: "Unduh Data Anda",
    downloadDataDesc: "Unduh salinan data Kollect Anda termasuk profil, posting, kampanye, dan pekerjaan.",
    downloadAsJSON: "📥 Unduh sebagai JSON",
    downloadAsCSV: "📊 Unduh sebagai CSV",
    selectLanguage: "Pilih Bahasa Anda",
    english: "English (EN)",
    indonesian: "Bahasa Indonesia (ID)",
    spanish: "Español (ES)",
    french: "Français (FR)",
    german: "Deutsch (DE)",
    japanese: "日本語 (JA)",
    chinese: "中文 (ZH)",
    updating: "Memperbarui...",
    goToLogin: "Ke Login",
    failedLoadProfile: "Gagal memuat profil",
    languageUpdated: "Bahasa berhasil diperbarui!",
    failedUpdateLanguage: "Gagal memperbarui bahasa",
  },
  es: {
    home: "Inicio",
    search: "Buscar",
    explore: "Explorar",
    messages: "Mensajes",
    notifications: "Notificaciones",
    create: "Crear",
    profile: "Perfil",
    work: "Trabajo",
    settings: "Configuración",
    logout: "Cerrar sesión",
    pengaturan: "Configuración",
    editProfil: "Editar Perfil",
    notificationsMenu: "Notificaciones",
    accountPrivacy: "Privacidad de la Cuenta",
    closeFriend: "Amigos Cercanos",
    blocked: "Bloqueados",
    archiving: "Archivado y Descarga",
    language: "Idioma",
    editProfilTitle: "Editar Perfil",
    loading: "Cargando...",
    uploading: "Subiendo...",
    ubahFoto: "Cambiar Foto",
    hapusFoto: "Eliminar Foto",
    name: "Nombre",
    username: "Nombre de Usuario",
    website: "Sitio Web",
    bio: "Biografía",
    gender: "Género",
    menyimpan: "Guardando...",
    kirim: "Enviar",
    notificationSettingsTitle: "Configuración de Notificaciones",
    accountPrivacyTitle: "Privacidad de la Cuenta",
    closeFriendTitle: "Amigos Cercanos",
    blockedTitle: "Usuarios Bloqueados",
    archivingTitle: "Archivado y Descarga de Datos",
    languageTitle: "Configuración de Idioma",
    remove: "Eliminar",
    unblock: "Desbloquear",
    downloadYourData: "Descargue Sus Datos",
    downloadDataDesc: "Descargue una copia de sus datos de Kollect incluyendo perfil, publicaciones, campañas y trabajos.",
    downloadAsJSON: "📥 Descargar como JSON",
    downloadAsCSV: "📊 Descargar como CSV",
    selectLanguage: "Seleccione Su Idioma",
    english: "English (EN)",
    indonesian: "Bahasa Indonesia (ID)",
    spanish: "Español (ES)",
    french: "Français (FR)",
    german: "Deutsch (DE)",
    japanese: "日本語 (JA)",
    chinese: "中文 (ZH)",
    updating: "Actualizando...",
    goToLogin: "Ir a Iniciar Sesión",
    failedLoadProfile: "Error al cargar el perfil",
    languageUpdated: "¡Idioma actualizado correctamente!",
    failedUpdateLanguage: "Error al actualizar el idioma",
  },
  fr: {
    home: "Accueil",
    search: "Rechercher",
    explore: "Explorer",
    messages: "Messages",
    notifications: "Notifications",
    create: "Créer",
    profile: "Profil",
    work: "Travail",
    settings: "Paramètres",
    logout: "Déconnexion",
    pengaturan: "Paramètres",
    editProfil: "Modifier le Profil",
    notificationsMenu: "Notifications",
    accountPrivacy: "Confidentialité du Compte",
    closeFriend: "Amis Proches",
    blocked: "Bloqués",
    archiving: "Archivage et Téléchargement",
    language: "Langue",
    editProfilTitle: "Modifier le Profil",
    loading: "Chargement...",
    uploading: "Téléchargement...",
    ubahFoto: "Changer la Photo",
    hapusFoto: "Supprimer la Photo",
    name: "Nom",
    username: "Nom d'Utilisateur",
    website: "Site Web",
    bio: "Biographie",
    gender: "Genre",
    menyimpan: "Enregistrement...",
    kirim: "Envoyer",
    notificationSettingsTitle: "Paramètres de Notification",
    accountPrivacyTitle: "Confidentialité du Compte",
    closeFriendTitle: "Amis Proches",
    blockedTitle: "Utilisateurs Bloqués",
    archivingTitle: "Archivage et Téléchargement de Données",
    languageTitle: "Paramètres de Langue",
    remove: "Supprimer",
    unblock: "Débloquer",
    downloadYourData: "Télécharger Vos Données",
    downloadDataDesc: "Téléchargez une copie de vos données Kollect incluant profil, publications, campagnes et travaux.",
    downloadAsJSON: "📥 Télécharger en JSON",
    downloadAsCSV: "📊 Télécharger en CSV",
    selectLanguage: "Sélectionnez Votre Langue",
    english: "English (EN)",
    indonesian: "Bahasa Indonesia (ID)",
    spanish: "Español (ES)",
    french: "Français (FR)",
    german: "Deutsch (DE)",
    japanese: "日本語 (JA)",
    chinese: "中文 (ZH)",
    updating: "Mise à jour...",
    goToLogin: "Aller à la Connexion",
    failedLoadProfile: "Échec du chargement du profil",
    languageUpdated: "Langue mise à jour avec succès!",
    failedUpdateLanguage: "Échec de la mise à jour de la langue",
  },
  de: {
    home: "Startseite",
    search: "Suche",
    explore: "Erkunden",
    messages: "Nachrichten",
    notifications: "Benachrichtigungen",
    create: "Erstellen",
    profile: "Profil",
    work: "Arbeit",
    settings: "Einstellungen",
    logout: "Abmelden",
    pengaturan: "Einstellungen",
    editProfil: "Profil Bearbeiten",
    notificationsMenu: "Benachrichtigungen",
    accountPrivacy: "Kontodatenschutz",
    closeFriend: "Enge Freunde",
    blocked: "Blockiert",
    archiving: "Archivierung und Download",
    language: "Sprache",
    editProfilTitle: "Profil Bearbeiten",
    loading: "Wird geladen...",
    uploading: "Wird hochgeladen...",
    ubahFoto: "Foto Ändern",
    hapusFoto: "Foto Löschen",
    name: "Name",
    username: "Benutzername",
    website: "Website",
    bio: "Biographie",
    gender: "Geschlecht",
    menyimpan: "Wird gespeichert...",
    kirim: "Absenden",
    notificationSettingsTitle: "Benachrichtigungseinstellungen",
    accountPrivacyTitle: "Kontodatenschutz",
    closeFriendTitle: "Enge Freunde",
    blockedTitle: "Blockierte Benutzer",
    archivingTitle: "Archivierung und Dateidownload",
    languageTitle: "Spracheinstellungen",
    remove: "Entfernen",
    unblock: "Entsperren",
    downloadYourData: "Ihre Daten Herunterladen",
    downloadDataDesc: "Laden Sie eine Kopie Ihrer Kollect-Daten herunter, einschließlich Profil, Beiträge, Kampagnen und Arbeit.",
    downloadAsJSON: "📥 Als JSON Herunterladen",
    downloadAsCSV: "📊 Als CSV Herunterladen",
    selectLanguage: "Wählen Sie Ihre Sprache",
    english: "English (EN)",
    indonesian: "Bahasa Indonesia (ID)",
    spanish: "Español (ES)",
    french: "Français (FR)",
    german: "Deutsch (DE)",
    japanese: "日本語 (JA)",
    chinese: "中文 (ZH)",
    updating: "Wird aktualisiert...",
    goToLogin: "Zur Anmeldung",
    failedLoadProfile: "Fehler beim Laden des Profils",
    languageUpdated: "Sprache erfolgreich aktualisiert!",
    failedUpdateLanguage: "Fehler beim Aktualisieren der Sprache",
  },
  ja: {
    home: "ホーム",
    search: "検索",
    explore: "探索",
    messages: "メッセージ",
    notifications: "通知",
    create: "作成",
    profile: "プロフィール",
    work: "作品",
    settings: "設定",
    logout: "ログアウト",
    pengaturan: "設定",
    editProfil: "プロフィールを編集",
    notificationsMenu: "通知",
    accountPrivacy: "アカウントプライバシー",
    closeFriend: "親友",
    blocked: "ブロック済み",
    archiving: "アーカイブとダウンロード",
    language: "言語",
    editProfilTitle: "プロフィールを編集",
    loading: "読み込み中...",
    uploading: "アップロード中...",
    ubahFoto: "写真を変更",
    hapusFoto: "写真を削除",
    name: "名前",
    username: "ユーザー名",
    website: "ウェブサイト",
    bio: "プロフィール",
    gender: "性別",
    menyimpan: "保存中...",
    kirim: "送信",
    notificationSettingsTitle: "通知設定",
    accountPrivacyTitle: "アカウントプライバシー",
    closeFriendTitle: "親友",
    blockedTitle: "ブロック済みユーザー",
    archivingTitle: "アーカイブとデータダウンロード",
    languageTitle: "言語設定",
    remove: "削除",
    unblock: "ブロック解除",
    downloadYourData: "データをダウンロード",
    downloadDataDesc: "プロフィール、投稿、キャンペーン、作品を含むKollectデータのコピーをダウンロードします。",
    downloadAsJSON: "📥 JSONとしてダウンロード",
    downloadAsCSV: "📊 CSVとしてダウンロード",
    selectLanguage: "言語を選択",
    english: "English (EN)",
    indonesian: "Bahasa Indonesia (ID)",
    spanish: "Español (ES)",
    french: "Français (FR)",
    german: "Deutsch (DE)",
    japanese: "日本語 (JA)",
    chinese: "中文 (ZH)",
    updating: "更新中...",
    goToLogin: "ログインへ",
    failedLoadProfile: "プロフィール読み込み失敗",
    languageUpdated: "言語が正常に更新されました!",
    failedUpdateLanguage: "言語更新失敗",
  },
  zh: {
    home: "首页",
    search: "搜索",
    explore: "探索",
    messages: "消息",
    notifications: "通知",
    create: "创建",
    profile: "个人资料",
    work: "作品",
    settings: "设置",
    logout: "登出",
    pengaturan: "设置",
    editProfil: "编辑个人资料",
    notificationsMenu: "通知",
    accountPrivacy: "账户隐私",
    closeFriend: "亲密好友",
    blocked: "已屏蔽",
    archiving: "存档和下载",
    language: "语言",
    editProfilTitle: "编辑个人资料",
    loading: "加载中...",
    uploading: "上传中...",
    ubahFoto: "更改照片",
    hapusFoto: "删除照片",
    name: "名称",
    username: "用户名",
    website: "网站",
    bio: "简介",
    gender: "性别",
    menyimpan: "保存中...",
    kirim: "提交",
    notificationSettingsTitle: "通知设置",
    accountPrivacyTitle: "账户隐私",
    closeFriendTitle: "亲密好友",
    blockedTitle: "已屏蔽的用户",
    archivingTitle: "存档和数据下载",
    languageTitle: "语言设置",
    remove: "删除",
    unblock: "取消屏蔽",
    downloadYourData: "下载您的数据",
    downloadDataDesc: "下载您的Kollect数据副本，包括个人资料、帖子、活动和作品。",
    downloadAsJSON: "📥 下载为JSON",
    downloadAsCSV: "📊 下载为CSV",
    selectLanguage: "选择您的语言",
    english: "English (EN)",
    indonesian: "Bahasa Indonesia (ID)",
    spanish: "Español (ES)",
    french: "Français (FR)",
    german: "Deutsch (DE)",
    japanese: "日本語 (JA)",
    chinese: "中文 (ZH)",
    updating: "更新中...",
    goToLogin: "前往登录",
    failedLoadProfile: "加载个人资料失败",
    languageUpdated: "语言更新成功!",
    failedUpdateLanguage: "语言更新失败",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['en', 'id', 'es', 'fr', 'de', 'ja', 'zh'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}